### ISSUE TITLE
Python3 examples

### ISSUE THREAD

**Issue by ryanbuckner** [pnbruckner/life360#11]
I'm using this outside of HA byt building a plugin for Indigo Domotics. The latest Life360 update broke the plugin and I may adopt this solution. I'm currently using [harperreed](https://github.com/harperreed) solution. 

I know you don't support outside of HA. But can you please provide a simple example of how to authenticate the API and grab circles / members and I'll figure out the rest?

**Comment by pnbruckner** [comment]
You can check out https://github.com/home-assistant/core/tree/dev/homeassistant/components/life360. If you'd like a simpler example, I could provide something maybe in a few days.

**Comment by ryanbuckner** [comment]
Thanks.  If you don’t mind.  No rush. Ryan ***@***.*** Dec 24, 2023, at 2:52 PM, Phil Bruckner ***@***.***> wrote:﻿
You can check out https://github.com/home-assistant/core/tree/dev/homeassistant/components/life360. If you'd like a simpler example, I could provide something maybe in a few days.

**Comment by ryanbuckner** [comment]
I was able to update [my Indigo Plugin](https://github.com/ryanbuckner/life360-plugin) from your solutions to the Cloudflare blocking problem. Thank you! 

Closing this issue

**Comment by pnbruckner** [comment]
FWIW:

```python
import asyncio

from life360 import Life360


async def main():
    username = input("username: ")
    password = input("password: ")
    api = Life360()
    try:
        authorization = await api.get_authorization(username, password)
        print("Authorization:", authorization)
    finally:
        await api.close()


asyncio.run(main())
```

**Comment by ryanbuckner** [comment]
Thanks Phil.

**Comment by andrewcincotta** [comment]
> FWIW:
> 
> ```python
> import asyncio
> 
> from life360 import Life360
> 
> 
> async def main():
>     username = input("username: ")
>     password = input("password: ")
>     api = Life360()
>     try:
>         authorization = await api.get_authorization(username, password)
>         print("Authorization:", authorization)
>     finally:
>         await api.close()
> 
> 
> asyncio.run(main())
> ```

Upon running this code I am getting this error:
missing 2 required positional arguments: 'session' and 'max_retries'

**Comment by pnbruckner** [comment]
@andrewcincotta that's because since that comment was made, the API has changed. If you want to use that code, then make sure you're installing version 6.0.1. The latest beta, v7.0.0b1, works a bit differently.

**Comment by ryanbuckner** [comment]
So this API is no longer dead?

**Comment by pnbruckner** [comment]
Hard to say. I'm trying to revive it.
