### ISSUE TITLE
Invalid_auth as of 3rd Jan 2024

### ISSUE THREAD

**Issue by T2evh** [pnbruckner/life360#13]
Installed local copy to custom components a couple of weeks which fixed the problem last time. However the issue has just started again. Last time it was due to me authenticating new phone number. This time I've made no changes. 

Hope you can help. Its a great integration which drives alot of home automations

Thanks

**Comment by pnbruckner** [comment]
I can confirm it is broken again. Life360 seems to possibly be trying to actively block use cases outside their official app (via Cloudflare, etc.) It appears it's time to give up.

**Comment by T2evh** [comment]
Phil,

Thanks for the update. Out of interest do you have any recommendations for
an alternative? I'll probably look at the companion app

Trevor

**Comment by pnbruckner** [comment]
If you want to use something people probably already have on their phones, try https://www.home-assistant.io/integrations/google_maps/. Other than that, I don't personally have any recommendations. There are many on the community forum, though.
