### ISSUE TITLE
Example Call for beta version 

### ISSUE THREAD

**Issue by ryanbuckner** [pnbruckner/life360#17]
Would you mind updating the read.me with a sample of how to use / test this new beta?  I think logging in and printing a list of members would be sufficient.

**Comment by pnbruckner** [comment]
I've never intended this package for "standalone" usage. It was intended for use by a Home Assistant integration. If someone can use it for other purposes, and can figure out how to do so, by all means. I don't plan on improving the docs to that end.

Having said that, you can look here for how the HA integration I'm working on uses it:

https://github.com/pnbruckner/ha-life360/blob/ede302c06652ddda524657fb40fc52e16e8bc1b9/custom_components/life360/coordinator.py#L567-L573

**Comment by ryanbuckner** [comment]
Understood. Thanks for all you're doing.

**Comment by pnbruckner** [comment]
Here's also a snippet from a test script I wrote:
```python
import asyncio

from aiohttp import ClientSession, ClientTimeout
from life360 import Life360

USERNAME = "someone@someplace.com"
PASSWORD = "someones_password"
MAX_RETRIES = 2
VERBOSITY = 4

async def main():
    session = ClientSession(timeout=ClientTimeout(15))
    try:
        api = Life360(session, MAX_RETRIES, verbosity=VERBOSITY)
        authorization = await api.login_by_username(USERNAME, PASSWORD)
        # Save authorization for future use if desired.
        # It can be passed into the Life360 constructor and then login_by_username isn't necessary.
        circles = api.get_circles()
        # ...
    finally:
        await session.close()

asyncio.run(main())
```

**Comment by ryanbuckner** [comment]
I appreciate it. Is the token no longer required? I got an error:

aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden',
url=URL('https://api-cloudfront.life360.com/v3/oauth2/token')

**Comment by ryanbuckner** [comment]
This times out for me. I'm able to log in using email address and password on the same laptop, but there's a captcha.  Anything I should try ?

**Comment by ryanbuckner** [comment]
This is working for me, thank you
